
# ##########################################################
# Package

[package]

authors = [
	"Matt Wilson <matthew@synesis.com.au>",
]
description = "Command-Line Argument Sorting and Parsing (for Rust)"
edition = "2021"
homepage = "https://github.com/synesissoftware/libpath.Rust"
license = "BSD-3-Clause"
name = "clasp-rs"
readme = "README.md"
version = "0.0.0"


# ##########################################################
# Targets


# ##########################################################
# Features

[features]


# ##########################################################
# Dependencies

[dependencies]


[dev-dependencies]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

